repos:
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.26
  hooks:
  - id: actionlint
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.19
  hooks:
  - id: shellcheck
    exclude: ^vendor/
- repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
  rev: v1.0
  hooks:
    - id: sops-encryption
      exclude: *.\.md
